name: release

on:
  workflow_dispatch:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set version env
      run: echo "CI_VERSION=$(cat src/version.go | grep 'BuildVersion =' | cut -d'"' -f2 | awk NF)" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: gameplayer8
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8,linux/riscv64
        push: true
        tags: |
          gameplayer8/compose-updater:${{ env.CI_VERSION }}
          gameplayer8/compose-updater:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: gameplayer8
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
        repository: gameplayer8/compose-updater
        readme-filepath: ./README.md
#    - name: Create Release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ env.CI_VERSION }}
#        release_name: ${{ env.CI_VERSION }}
#        draft: false
#        prerelease: false
