name: test

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build integration test image
      run: docker build -t compose-test -f test.Dockerfile .
    - name: Run integration test
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro -t compose-test
